server:
  port: 7001

eureka:
  instance:
    # hostname: localhost  #eureka服务端的实例名字 单机版
    hostname: eureka7001.com  #eureka服务端的实例名字 集群版
    lease-renewal-interval-in-seconds: 1 # 心跳时长，单位秒
    lease-expiration-duration-in-seconds: 1 # 心跳终止后延期删除时长，单位秒
  client:
    register-with-eureka: false    #表识不向注册中心注册自己
    fetch-registry: false          #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址 单机版
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址 集群版
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    enable-self-preservation: false #是否关闭自我保护模式，默认是开启的